Added methods getAttributeSetId getEntityTypeId
Vinai/VinaiKopp_EavOptionSetup pull request #3
Opened 2017-05-30 10:17 UTC by bordeo

migrate methods getAttributeSetId getAttributeSet getEntityTypeId getEntityType

2017-06-22 07:40 UTC, Vinai requested changes
Thank you very much for your PR!  
Sorry I'm reviewing it so late, I had missed the email notification.
There are a few minor changes I would like to ask you to make, then I'm very happy to merge.

In addition to the small change requests, I noticed you sometimes use double and sometimes single quoted  strings, without any reason I could discern.  
It's not important, but it would satisfy my OCD if you would use single quote strings, unless they contain an embedded variable or `\n`.

Also, in the PHPDoc comments the capitalization of the comments is not quite consistent, e.g. `id` in one vs. `Id` in another. I don't mind merging with this inconsistencies, but I thought I'd mention them because I appreciate that level of feedback in code reviews for my own code. I hope you don't mind.

Thanks again for the PR!

2017-06-22 07:40 UTC, Vinai commented on Setup/EavOptionSetup.php
> +    private $resurceConnection;
Typo: `$resurceConnection` is missing an `o` in `resource`.

2017-06-22 07:40 UTC, Vinai commented on Setup/EavOptionSetup.php
> +        ResourceConnection $resurceConnection
Typo: `$resurceConnection` is missing an `o` in `resource` (same as above, just for the constructor argument variable name).

2017-06-22 07:40 UTC, Vinai commented on Setup/EavOptionSetup.php
> +     * @return mixed
Maybe `@return int|string|null`? Then it's at least clear it does not return a compound type.

2017-06-22 07:40 UTC, Vinai commented on Setup/EavOptionSetup.php
> +     * @return mixed
Same for the return type here as above, I think `string|int|null` would be more helpful than `mixed`.

2017-06-22 13:38 UTC, bordeo commented
Hi Vinai
thank you for your review, I fix all kind of stuff. I hope now it's all good.

PS: I copied the methods from magento core changing very few things. PHPDoc and quotes remained the same.

Thank you

2018-03-11 10:30 UTC, bordeo commented
Hi Vinai
there are other problems with my pull request?

2018-03-11 11:21 UTC, Vinai approved these changes

2018-03-11 11:22 UTC, Vinai commented
I'm sorry, I just missed the update notification! Thanks for picking up the thread again!

2018-03-11 11:22 UTC, merged